apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    service: payment
    stage: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payment
      stage: prod
  template:
    metadata:
      labels:
        service: payment
        stage: prod
    spec:
      containers:
      - name: payment
        image: mitultan/payment:v2
        #image: {{ .Values.image.repo }}/rs-payment:{{ .Values.image.version }}
        imagePullPolicy: IfNotPresent
        # agent networking access
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: JAEGER_HOST_NAME
            value: "localhost"
          - name: JAEGER_HOST_PORT
            value: "6831"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
            # sidecar agent
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent:1.30.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5775
            name: zk-compact-trft
            protocol: UDP
          - containerPort: 5778
            name: config-rest
            protocol: TCP
          - containerPort: 6831
            name: jg-compact-trft
            protocol: UDP
          - containerPort: 6832
            name: jg-binary-trft
            protocol: UDP
          - containerPort: 14271
            name: admin-http
            protocol: TCP
        args:
          #- --reporter.grpc.host-port=dns:///jaeger-collector-headless.observability:14250
          - --reporter.type=grpc
          - --reporter.grpc.host-port=wavefront-proxy.default:14250
  # telegraf-wavefront sidecar
      - name: telegraf
        image: wavefronthq/telegraf-sidecar
        ports:
        - name: udp-statsd
          containerPort: 8125
        - name: udp-8092
          containerPort: 8092
        - name: tcp-8094
          containerPort: 8094
        env:
        - name: WAVEFRONT_PROXY
          value: wavefront-proxy.default
        - name: WAVEFRONT_PROXY_PORT
          value: "2878"
        - name: INTERVAL
          value: 60s
        - name: METRIC_SOURCE_NAME
          value: payment
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: telegraf-d
          mountPath: /etc/telegraf/telegraf.d  
      volumes:
      - name: telegraf-d
        projected:
          sources:
          - configMap:
              name: telegraf-prometheus-config-payment
      restartPolicy: Always
