apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-prometheus-config-cart
  namespace: robot-shop
data:
  prometheus.conf: |
    [[inputs.prometheus]]
      ## An array of urls to scrape metrics from.
      urls = ["http://192.168.131.52:31260/api/cart/metrics"]
      ## Use bearer token for authorization
      # bearer_token = /path/to/bearer/token
      ## Specify timeout duration for slower prometheus clients (default is 3s)
      # response_timeout = "3s"
      ## Optional SSL Config
      # ssl_ca = /path/to/cafile
      # ssl_cert = /path/to/certfile
      # ssl_key = /path/to/keyfile
      ## Use SSL but skip chain & host verification
      # insecure_skip_verify = false
      # Specify optional tags to be applied to all metrics for this plugin
      # NOTE: Order matters, this needs to be at the end of the plugin definition
      # [[inputs.prometheus.tags]]
        # tag1 = "foo"
        # tag2 = "bar"